### ISSUE TITLE
Dark notification text and bright white calendar in Ubuntu 20.04

### ISSUE THREAD

**Issue by Akin909** [EliverLara/Ant-Dracula#41]
Firstly, thanks for the awesome theme :rocket:

I recently updated to Ubuntu 20.04 beta and noticed that the notification bodies now have dark text similar to #25 and the calendar is bright white. Think this might have been caused by a regression in 20.04. ~I've tried taking a screenshot but notifications menu always disappears when I try and screenshot it~

![Ant Dracula bug](https://user-images.githubusercontent.com/22454918/78781358-03904d80-7998-11ea-95cf-77e0616a73f3.jpg)

**Comment by owainharris** [comment]
Same issue here. In Gnome 3.36, the calendar description is unreadable. Tried modifying the CSS, but couldn't find what controls this particular element. 

![2020-04-22_13-38](https://user-images.githubusercontent.com/11605363/80015008-1f6b1780-849f-11ea-9d25-39a4f65412d1.png)

**Comment by EliverLara** [comment]
That was fixed!

**Comment by cenktaskin** [comment]
Hello there, sorry for bugging. 
I just installed the theme and enjoying it. 
But have the same problem as described here, notifications are not readable. Please check the screenshot here:
![Screenshot from 2022-01-26 01-57-02](https://user-images.githubusercontent.com/42993892/151085572-bd15969b-f4ee-406f-810f-25f8545299a5.png)
When I disable the extension:
![Screenshot from 2022-01-26 02-04-35](https://user-images.githubusercontent.com/42993892/151085670-8c1f4565-5276-4fc6-bbc8-7e8d0ed5e117.png)
Seems like it is caused by the extension Notificaiton Center 
https://github.com/Selenium-H/Notification-Center
Is there anything I can accomplish by modifying something? 
Apologies if the only about the NC extension.
